services:
  indexer:
    build: .
    image: domain-rag:latest
    entrypoint: ["python", "scripts/build_index.py"]
    env_file:
      - .env.local
    volumes:
      - ./llm:/app/llm
      - ./artifacts:/app/artifacts
      - ./config:/app/config:ro

  api:
    build: .
    image: domain-rag:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    environment:
      - OPENAI_CHAT_MODEL=gpt-4o-mini
      - OPENAI_EMBED_MODEL=text-embedding-3-small
    volumes:
      - ./artifacts:/app/artifacts:ro
      - ./config:/app/config:ro
      - ./llm:/app/llm:ro
    # indexは必要時に手動実行。既にartifactsがある場合はそのまま起動可。
